services:
  app:
    build: .
    container_name: erp-system
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: erp-system-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_erp_system:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data_erp_system: